name: custom_ui
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
description: Custom ui flutter package
version: 0.0.4
homepage:

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.8
  flutter_svg: any
  json_annotation: any
  google_mobile_ads: ^5.1.0

  custom_data:
    git:
      url: https://github.com/dvmatyun/flutter_data_aim.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  json_serializable: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/svg/flags/
